name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        shell: pwsh
        env:
          DEMOMODULEPSG: ${{ secrets.POWERSHELL_GALLERY_API_KE }}
          BUILDVER: "0.1.0"
        run: |
          ./build_scripts/build.ps1
          if (Test-Path ../DemoModule1) {
            Write-Host "Building and publishing module..."
            Publish-Module -Path ../DemoModule1 -Repository PSGallery -NuGetApiKey $env:DEMOMODULEPSG -Verbose
          } else {
            Write-Error "DemoModule1 folder not found."
            exit 1
          }
