name: Publish
on: [workflow_dispatch]

jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Publish
          env:
            APIKEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
          run: .\build_scripts\build.ps1
          shell: pwsh